# Generated by Django 2.1 on 2018-09-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racun',
            name='ukupni_iznos',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='ukupni iznos'),
        ),
    ]
