# Generated by Django 2.1 on 2018-09-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasa', '0002_auto_20180918_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='racun',
            name='ukupno_osnovica',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='ukupno osnovica'),
        ),
        migrations.AddField(
            model_name='racun',
            name='ukupno_porez',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='ukupno porez'),
        ),
        migrations.AlterField(
            model_name='stavkaracuna',
            name='rbr',
            field=models.IntegerField(default=0, verbose_name='redni broj'),
        ),
    ]
