# Generated by Django 2.1 on 2018-09-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasa', '0003_auto_20180918_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zaposlenik',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='email address'),
        ),
    ]
