# Generated by Django 2.1 on 2018-09-25 07:22

from django.db import migrations, models
import kasa.validators


class Migration(migrations.Migration):

    dependencies = [
        ('kasa', '0004_auto_20180921_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvrtka',
            name='inicijalizacija',
            field=models.BooleanField(default=False, verbose_name='inicijalizacija'),
        ),
        migrations.AlterField(
            model_name='kupac',
            name='oib',
            field=models.CharField(blank=True, max_length=11, validators=[kasa.validators.validate_OIB], verbose_name='OIB'),
        ),
        migrations.AlterField(
            model_name='poslovnica',
            name='adresa',
            field=models.CharField(blank=True, max_length=150, verbose_name='adresa'),
        ),
        migrations.AlterField(
            model_name='poslovnica',
            name='mjesto',
            field=models.CharField(blank=True, max_length=150, verbose_name='mjesto'),
        ),
    ]
